//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado.Net.Ls5.DBFirst_EF.Date._010224.DBFirstModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirPlane
    {
        public int Id { get; set; }
        public string BrandName { get; set; }
        public int SchedulId { get; set; }
        public int PilotId { get; set; }
    
        public virtual Pilot Pilot { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
