//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado.Net.Ls5.DBFirst_EF.Date._010224.DBFirstModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirLanesDBEntities1 : DbContext
    {
        public AirLanesDBEntities1()
            : base("name=AirLanesDBEntities1")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AirPlane> AirPlanes { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Pilot> Pilots { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
    }
}
